# Generated by Django 5.2.4 on 2025-07-14 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_article_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
